### ISSUE TITLE
Create a nicer index page for repositories

### ISSUE THREAD

**Issue by matteodelabre** [toltec-dev/toltec#21]
Visiting https://toltec.delab.re/stable or https://toltec.delab.re/testing should show a nicely formatted list of packages sorted by category, with the following information for each package:

* Name and link to project home page
* License
* Download link
* Size
* SHA-256 sum

This index page should be automatically generated through GitHub Actions.

**Comment by raisjnn** [comment]
I'll be glad to help with this later this week if it's not too late by then
