### ISSUE TITLE
Move toltec to a GitHub organization

### ISSUE THREAD

**Issue by matteodelabre** [toltec-dev/toltec#32]
> I also propose that the individual repos should go under a single organization name (vs. putting them into matteo namespace).
> _Originally posted by @raisjnn in https://github.com/matteodelabre/toltec/pull/29#issuecomment-691329742_

---

> > I also propose that the individual repos should go under a single organization name (vs. putting them into matteo namespace).
>
> I agree that it’s best if the repository is not tied to my personal GitHub account. Do you suggest creating an org specific to toltec or joining an existing org like @reHackable (if that’s even possible)?
>
> _Originally posted by @matteodelabre in https://github.com/matteodelabre/toltec/pull/29#issuecomment-691350712_

**Comment by Eeems** [comment]
I would be okay with this joining @reHackable There would have to be some discussion with them about what that means, and if their philosophy matches with what we want here.

**Comment by okayzed** [comment]
what's the purpose in joining rehackable? i think make: "remarkable-toltec" or "toltec-dev" organization (or any other name that sounds good :) ) and move forward while the discussions get started. then if it makes sense, merge them together down the line

**Comment by raisjnn** [comment]
what's the purpose in joining rehackable? i think make: "remarkable-toltec" or "toltec-dev" organization (or any other name that sounds good :) ) and move forward while the discussions get started. then if it makes sense, merge them together down the line

(commented with wrong name before)
